// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dedup.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertProcessedEventOnce = `-- name: InsertProcessedEventOnce :execrows
INSERT INTO click_processed_events (
    event_id,
    processed_at
) VALUES (
    $1, $2
)
ON CONFLICT (event_id) DO NOTHING
`

type InsertProcessedEventOnceParams struct {
	EventID     string             `json:"event_id"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

func (q *Queries) InsertProcessedEventOnce(ctx context.Context, arg InsertProcessedEventOnceParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertProcessedEventOnce, arg.EventID, arg.ProcessedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
