// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ClickOutbox struct {
	ID                  pgtype.UUID        `json:"id"`
	EventType           string             `json:"event_type"`
	Slug                string             `json:"slug"`
	OccurredAt          pgtype.Timestamptz `json:"occurred_at"`
	Traceparent         pgtype.Text        `json:"traceparent"`
	Tracestate          pgtype.Text        `json:"tracestate"`
	Baggage             pgtype.Text        `json:"baggage"`
	Status              string             `json:"status"`
	Attempts            int32              `json:"attempts"`
	NextAttemptAt       pgtype.Timestamptz `json:"next_attempt_at"`
	LastError           pgtype.Text        `json:"last_error"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ProcessingOwner     pgtype.Text        `json:"processing_owner"`
	ProcessingExpiresAt pgtype.Timestamptz `json:"processing_expires_at"`
	SentAt              pgtype.Timestamptz `json:"sent_at"`
}

type ClickProcessedEvent struct {
	EventID     string             `json:"event_id"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

type ClicksDaily struct {
	Slug  string      `json:"slug"`
	Day   pgtype.Date `json:"day"`
	Count int64       `json:"count"`
}

type Link struct {
	Slug      string             `json:"slug"`
	Url       string             `json:"url"`
	Notes     pgtype.Text        `json:"notes"`
	ApiKey    pgtype.Text        `json:"api_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Clicks    int64              `json:"clicks"`
}
