// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	ClaimNextOutboxEvent(ctx context.Context, arg ClaimNextOutboxEventParams) (ClickOutbox, error)
	CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error)
	DeleteDailyStatsBySlug(ctx context.Context, slug string) error
	DeleteLinkBySlug(ctx context.Context, slug string) (int64, error)
	EnqueueClickOutbox(ctx context.Context, arg EnqueueClickOutboxParams) (ClickOutbox, error)
	GetActiveLinkBySlug(ctx context.Context, arg GetActiveLinkBySlugParams) (Link, error)
	GetActiveLinkBySlugAndIncClick(ctx context.Context, arg GetActiveLinkBySlugAndIncClickParams) (Link, error)
	GetDailyStatsByRange(ctx context.Context, arg GetDailyStatsByRangeParams) ([]ClicksDaily, error)
	GetLinkBySlug(ctx context.Context, slug string) (Link, error)
	IncDailyClick(ctx context.Context, arg IncDailyClickParams) error
	InsertProcessedEventOnce(ctx context.Context, arg InsertProcessedEventOnceParams) (int64, error)
	MarkOutboxRetry(ctx context.Context, arg MarkOutboxRetryParams) (int64, error)
	MarkOutboxSent(ctx context.Context, arg MarkOutboxSentParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
