// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: stats.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDailyStatsBySlug = `-- name: DeleteDailyStatsBySlug :exec
DELETE FROM clicks_daily WHERE slug = $1
`

func (q *Queries) DeleteDailyStatsBySlug(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, deleteDailyStatsBySlug, slug)
	return err
}

const getDailyStatsByRange = `-- name: GetDailyStatsByRange :many
SELECT slug, day, count
FROM clicks_daily
WHERE slug = $1
  AND day >= $2
  AND day <= $3
ORDER BY day ASC
`

type GetDailyStatsByRangeParams struct {
	Slug  string      `json:"slug"`
	Day   pgtype.Date `json:"day"`
	Day_2 pgtype.Date `json:"day_2"`
}

func (q *Queries) GetDailyStatsByRange(ctx context.Context, arg GetDailyStatsByRangeParams) ([]ClicksDaily, error) {
	rows, err := q.db.Query(ctx, getDailyStatsByRange, arg.Slug, arg.Day, arg.Day_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClicksDaily{}
	for rows.Next() {
		var i ClicksDaily
		if err := rows.Scan(&i.Slug, &i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incDailyClick = `-- name: IncDailyClick :exec
INSERT INTO clicks_daily (slug, day, count)
VALUES ($1, $2, 1)
ON CONFLICT (slug, day)
DO UPDATE SET count = clicks_daily.count + 1
`

type IncDailyClickParams struct {
	Slug string      `json:"slug"`
	Day  pgtype.Date `json:"day"`
}

func (q *Queries) IncDailyClick(ctx context.Context, arg IncDailyClickParams) error {
	_, err := q.db.Exec(ctx, incDailyClick, arg.Slug, arg.Day)
	return err
}
